"""1683122910_update

Revision ID: 1c31cfa68a4e
Revises: 
Create Date: 2023-05-03 17:08:30.411584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c31cfa68a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('size_cols', sa.Integer(), nullable=False),
    sa.Column('size_rows', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_table('dataset_registry_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_registry_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('original_dtype', sa.String(), nullable=False),
    sa.Column('converted_dtype', sa.String(), nullable=False),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('min_value_num', sa.Float(), nullable=True),
    sa.Column('max_value_num', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_registry_id'], ['dataset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployable_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_registry_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_mapping', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('estimator_type', sa.String(), nullable=False),
    sa.Column('estimator_class', sa.String(), nullable=False),
    sa.Column('deployable', sa.LargeBinary(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_registry_id'], ['dataset_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('model_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployable_id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('request_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployable_id'], ['deployable_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_log_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_log_id'], ['model_execution_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_items_id', sa.Integer(), nullable=False),
    sa.Column('varname', sa.String(), nullable=False),
    sa.Column('in_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['execution_items_id'], ['execution_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_items_id', sa.Integer(), nullable=False),
    sa.Column('classname', sa.String(), nullable=True),
    sa.Column('out_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['execution_items_id'], ['execution_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_items')
    op.drop_table('request_items')
    op.drop_table('execution_items')
    op.drop_table('model_execution_log')
    op.drop_table('deployable_registry')
    op.drop_table('dataset_registry_columns')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
