"""1680186594_update

Revision ID: deaf60367529
Revises: 
Create Date: 2023-03-30 17:29:54.401369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaf60367529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('row_size', sa.Integer(), nullable=True),
    sa.Column('col_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('column', sa.String(), nullable=True),
    sa.Column('dtype', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['data_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_definitions')
    op.drop_table('data_registry')
    # ### end Alembic commands ###
